### ISSUE TITLE
[Request] Do not output formatted template in verify mode

### ISSUE THREAD

**Issue by bryanburke** [awslabs/aws-cloudformation-template-formatter#12]
When running in verify mode (`-v`/`--verify`), `cfn-format` still outputs the properly formatted template to stdout. This behavior can result in noisy output, especially when checking large templates within a CI pipeline. Would it be possible for `cfn-format --verify` to behave similarly to [gofmt -l](https://golang.org/cmd/gofmt/) or [black --check](https://github.com/psf/black), printing only whether or not the file is properly formatted?

**Comment by ctd** [comment]
Thanks for reporting this issue.

You're right - the current behaviour can be a bit verbose for use-cases I can think of, and perhaps a bit surprising compared to the help text for the option.

Until we fix this, a workaround could be to redirect stderr output from cfn-format to elsewhere (such as /dev/null) in your pipeline.

@stilvoid - do you recall any reasoning/context around the current behaviour that I'm not thinking of? I'd be inclined at this stage to remove printing the template from the verify behaviour.

**Comment by stilvoid** [comment]
@ctd Nope, it was just a minimal change to introduce the `-v` flag. I completely agree that it should match other tools and not output when valid :+1:

**Comment by ctd** [comment]
Fixed in https://github.com/awslabs/aws-cloudformation-template-formatter/pull/15
