### ISSUE TITLE
[Request] Ignore blank line at end of file

### ISSUE THREAD

**Issue by bryanburke** [awslabs/aws-cloudformation-template-formatter#13]
Many code editors such as VS Code are configurable to append a single blank line to the end of a file when saving. When using that setting, the act of saving a template and thus appending that empty line causes `cfn-format` to see the file as improperly formatted even if every other line follows the formatting rules. Would it be possible for `cfn-format` to ignore the trailing blank line if it exists?

**Comment by stilvoid** [comment]
Fixed in 7a47d7467c9f4210b17ba2f6128c0d392a90b216
