### ISSUE TITLE
glibc error with latest release binary

### ISSUE THREAD

**Issue by rburchill** [awslabs/aws-cloudformation-template-formatter#17]
Heads up, there might be an issue with the latest release binaries. I see a glibc error when running it. I'm running Ubuntu 20.04 Kernel 5.4.0-52-generic

Installing via goget works.

```bash
ldd cfn-format
./cfn-format: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./cfn-format)
	linux-vdso.so.1 (0x00007ffc5abde000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f181902d000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1818e3b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1819077000)
```

From googling, it looks like the release might have been built with a newer glibc than I have. That's assuming this issue isn't just local to myself.

**Comment by stilvoid** [comment]
Thanks for reporting this. I'll replace the binaries soon.

**Comment by stilvoid** [comment]
Rebuild using GitHub actions which are based on ubuntu 18.04 so [these](https://github.com/awslabs/aws-cloudformation-template-formatter/releases/tag/v1.1.2-1) should work ok for you.
