### ISSUE TITLE
Check mode: Exit non-zero if changes were made

### ISSUE THREAD

**Issue by kadrach** [awslabs/aws-cloudformation-template-formatter#5]
An equivalent of `terraform fmt -check=true`, and many tools like it, would be nice to have. 

> Check if the input is formatted. Exit status will be 0 if all input is properly formatted and non-zero otherwise

**Comment by stilvoid** [comment]
Great idea, I'll add that in soon :)

**Comment by stilvoid** [comment]
Fixed in #6 and will be in the next release
